export let words = [
  {
    category: "Food",
    list: [
      "Pizza",
      "Hamburger",
      "Sushi",
      "Pasta",
      "Lasagna",
      "Chocolate",
      "Fish",
    ],
  },
  {
    category: "City",
    list: [
      "Rome",
      "Paris",
      "Tirana",
      "Florence",
      "Venice",
      "Milano",
      "London",
      "Tokyo",
      "Berlin",
    ],
  },
  {
    category: "Car",
    list: [
      "Ferrari",
      "Hummer",
      "Ford",
      "Opel",
      "Toyota",
      "Tesla",
      "Mercedes",
      "Fiat",
      "BMW",
      "Lamborghini",
      "Maserati",
      "Audi",
      "Jeep",
      "Bugatti",
      "Chervolete",
      "Volkswagen",
      "Lexus",
      "Renault",
      "Skoda",
    ],
  },
  {
    category: "Fashion Brand",
    list: [
      "Adidas",
      "Nike",
      "Gucci",
      "Zara",
      "Puma",
      "Reebook",
      "Timberland",
      "Chanel",
      "Armani",
      "Rolex",
      "Givenchy",
      "Fendy",
      "Versace",
    ],
  },
  {
    category: "Sport",
    list: [
      "Football",
      "Soccer",
      "Basketball",
      "Volleyball",
      "Box",
      "Swimming",
      "Hockey",
      "Skiing",
      "Tennis",
      "Badminton",
      "Cricket",
    ],
  },
];
